Develop into master
rineless/exercises pull request #16
Opened 2020-09-01 22:27 UTC by rineless

2020-09-10 14:25 UTC, TetianaIefimenko requested changes

2020-09-10 14:25 UTC, TetianaIefimenko commented on src/Application.java
> +        List<Student> studentList = receiveListOfStudents("src/data/StudentData.csv");
try to use relative paths. After compilation you don't have such folder structure.

2020-09-10 14:25 UTC, TetianaIefimenko commented on src/Application.java
> +        studentsToAdd.add("13,Rubel,Bare,m,15.02.1998,German,Bremen,payable,0,present,rubel.bare@gmail.com");
to add a student you need to construct a java object and convert it in a string in your code

2020-09-10 14:25 UTC, TetianaIefimenko commented on src/Application.java
> +        lineList.remove(0);
you can do this operation in the stream using `skip()`

2020-09-10 14:25 UTC, TetianaIefimenko commented on src/model/group/Abbreviation.java
> +public enum Abbreviation {
please, rename it `GroupNames` or give another descriptive name

2020-09-10 14:25 UTC, TetianaIefimenko commented on src/model/group/Group.java
> +    private boolean onlineAccess;
boolean variables usually have names `is**`

2020-09-10 14:25 UTC, TetianaIefimenko commented on src/util/parser/SeparatedValuesParser.java
> +        return null;
please, don't return null, return empty value or throw an exception

2020-09-10 14:25 UTC, TetianaIefimenko commented on src/util/reader/FileReader.java
> +            if (Files.exists(Path.of(path)) && Files.isReadable(Path.of(path)))
The path may specify a directory. Please, add an appropriate check for this case.

2020-09-18 12:41 UTC, rineless commented on src/Application.java
> +        List<Student> studentList = receiveListOfStudents("src/data/StudentData.csv");
`Path current = Path.of(".");

        System.out.println("Students:");
        List<Student> studentList = receiveListOfStudents(current.toString() + "/src/data/StudentData.csv");
        studentList.stream().forEach(student -> System.out.println(student.toString()));

        System.out.println("Groups:");
        List<Group> groupList = receiveListOfGroups(current.toString() + "/src/data/StudentGroupData.csv");
        groupList.stream().forEach(group -> System.out.println(group.toString()));`

2020-09-18 13:03 UTC, rineless commented on src/Application.java
> +        studentsToAdd.add("13,Rubel,Bare,m,15.02.1998,German,Bremen,payable,0,present,rubel.bare@gmail.com");
`List<Student> studentsToAdd = new ArrayList<>();
        studentsToAdd.add(new Student().setId(13).setName("Rubel").setSurname("Bare").setGender(Gender.MALE)
                .setBirthDate(LocalDate.of(1998,2,15)).setCitizenship("German").setPlaceOfBirth("Bremen")
                .setTypeOfContract(TypeOfContract.PAYABLE).setGroupId(0).setTypeOfStudying(TypeOfStudying.PRESENT).setContactInformation("rubel.bare@gmail.com"));
        addStudents(studentsToAdd,studentList,current.toString() + "/src/data/StudentData.csv");`

2020-09-18 13:11 UTC, rineless commented on src/Application.java
> +        lineList.remove(0);
`FileReader studentReader = new FileReader();

        return studentReader.receiveLinesAsList(path).stream()
                .map(line -> new CSVParser().parseLineToStudent(line)).collect(Collectors.toList());`

2020-09-19 17:53 UTC, rineless commented on src/model/group/Group.java
> +    private boolean onlineAccess;
`private boolean isOnlineAccessible;`

2020-09-19 17:55 UTC, rineless commented on src/model/group/Abbreviation.java
> +public enum Abbreviation {
`public enum GroupNames`

2020-09-20 00:04 UTC, rineless commented on src/util/parser/SeparatedValuesParser.java
> +        return null;
`public String[] parseLineToArray(String line) {
        if (line != null && !line.contentEquals("")) {
            return line.split(separator_regex);
        }
        return new String[]{};
    }`

2020-09-20 00:17 UTC, rineless commented on src/util/reader/FileReader.java
> +            if (Files.exists(Path.of(path)) && Files.isReadable(Path.of(path)))
`public List<String> receiveLinesAsList(String path) {
        try {
            if (Files.exists(Path.of(path)) && Files.isRegularFile(Path.of(path))
                    && Files.isReadable(Path.of(path)))`

2020-09-24 16:04 UTC, merged